# Generated by Django 5.0.1 on 2024-01-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateTimeField()),
                ('canal', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=100)),
                ('detalhes', models.TextField()),
                ('locacao', models.CharField(max_length=100)),
            ],
        ),
    ]
