# Generated by Django 5.0.1 on 2024-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='data_evento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interacao',
            name='motivo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interacao',
            name='motivo2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interacao',
            name='ocasiao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interacao',
            name='primeira_cor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interacao',
            name='segunda_cor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interacao',
            name='tamanho',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='locacao',
            field=models.CharField(default='', max_length=100),
        ),
    ]
