# Generated by Django 5.0.1 on 2024-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interacao_data_evento_interacao_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='data_contato',
            field=models.CharField(default='', max_length=100),
        ),
    ]
